### ISSUE TITLE
Test #6.

### ISSUE THREAD

**Issue by ElayGelbart** [suvelocity/Mp3PlayerTask#4]
in Test number 6 mocksong3 duration is in the wrong format, is should be only seconds but its string in the MM:SS format.

```js
const mockSong3Details = [
  mockSong3.title,
  mockSong3.album,
  mockSong3.artist,
  mockSong3.duration, //this is the changed line
  mockSong3.id,
]

in my opinion this is the right way
```

**Comment by shaharkamay** [comment]
in my opinion you have a mistake, they wanted to give the 'addSong' function a duration variable in mm:ss format.
pay attention that if they change the line to what u suggested, the duration value will be the number 242.

**Comment by ElayGelbart** [comment]
the duration value in the original test#6 was odd and not in the right format, its more right to add a throw to the function or convert it to seconds

**Comment by shaharkamay** [comment]
That's an option but I guess they didn't want us to see how they convert seconds to mm:ss so we wouldn't copy from them.

**Comment by TswusayonaTsamsiyu** [comment]
Shahar has a point :)
